ARG WP_VERSION
ARG PHP_VERSION
ARG DOCKER_REGISTRY
ARG ACF_LICENSE_KEY
ARG ACF_PRO
ARG ACF_VERSION

FROM ${DOCKER_REGISTRY:-}wp-graphql-testing:latest-wp${WP_VERSION}-php${PHP_VERSION}

# Move the base image app setup script out of the way
# Put our shell script in place which will invoke the base image script
RUN cp /usr/local/bin/app-setup.sh /usr/local/bin/original-app-setup.sh
COPY docker/app.setup.sh /usr/local/bin/app-setup.sh

ENV PROJECT_DIR="${PLUGINS_DIR}/wp-graphql-acf-redux"

RUN echo "pcov.directory = /var/www/html/wp-content/plugins/wp-graphql-acf-redux" >> /usr/local/etc/php/conf.d/docker-php-ext-pcov.ini
