<?php

namespace Tests\WPGraphQLAcf\Functional;

use FunctionalTester;

abstract class AcfeProFieldCest extends AcfFieldCest {

	public function _before( FunctionalTester $I ): void {
		$I->loginAsAdmin();
		$I->amOnPluginsPage();
		if ( ! $I->see( 'Advanced Custom Fields: Extended PRO', '//td[contains(@class, "plugin-title")]' ) ) {
			$I->markTestSkipped( 'ACF Extended Pro is not active' );
		}
		parent::_before( $I ); // TODO: Change the autogenerated stub
	}

}
