<?php

namespace Tests\WPGraphQLAcf\Functional;

use FunctionalTester;

abstract class AcfeFieldCest extends AcfFieldCest {

	/**
	 * @param FunctionalTester $I
	 *
	 * @return void
	 */
	public function _before( FunctionalTester $I ): void {
		$I->loginAsAdmin();
		$I->amOnPluginsPage();
		$I->see( 'Advanced Custom Fields: Extended', '//td[contains(@class, "plugin-title")]'  );
		parent::_before( $I ); // TODO: Change the autogenerated stub
	}

}
