<?php

namespace Tests\WPGraphQLAcf\Functional;

use FunctionalTester;

abstract class AcfProFieldCest extends AcfFieldCest {

	public function _before( FunctionalTester $I ): void {
		$I->loginAsAdmin();
		$I->amOnPluginsPage();
		if ( ! $I->dontSeePluginInstalled( 'advanced-custom-fields-pro' ) ) {
			$I->markTestSkipped( 'ACF PRO is not active so this test will not run.' );
		}
		parent::_before( $I ); // TODO: Change the autogenerated stub
	}

}
