<?php

class AcfCloneFieldTestCase extends \Tests\WPGraphQLAcf\WPUnit\AcfFieldTestCase {

	public function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown(): void {
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

}
